### ISSUE TITLE
(Question) Deploying ctsms on amazon AWS

### ISSUE THREAD

**Issue by wolass** [phoenixctms/ctsms#2]
I have deployed the app on aws instance micro EC2. I have installed it using the install.sh script and opened ports 443 and 80. 

The problem is that I get the service unavailible  error 503 from apache. 

Is this a permissions issue?
if so any tips what to look for to fix this?
website: https://ec2-54-187-152-16.us-west-2.compute.amazonaws.com/portal.jsf

**Comment by rkrenn** [comment]
seems like tomcat failed to start - which most likely means it failed to compile the war somewhere before. how many ram and disk does that micro have, and is the instance able to connect to github websites/repos?

maybe you have the transcript of the install.sh run captured?

although i had it running on an e2c environment once long time ago, i otherwise need to run the commands from the install.sh one by one on such instance myself.

**Comment by rkrenn** [comment]
maven/androMDA running with 1gb of ram could be an issue; ill try that locally and report back.
did you manage to bring it up on a local virtualbox env?

**Comment by wolass** [comment]
I have increased to a bigger instance 

this is what shows up:

```
18.01.2018 20:03:15 com.mchange.v2.resourcepool.BasicResourcePool [com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0]
WARN  com.mchange.v2.resourcepool.BasicResourcePool$AcquireTask@57fcca7b -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception: 
org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

**Comment by rkrenn** [comment]
does the instance have more than one eth interfaces? maybe postgres bound to the wrong one.

cou can adjust the db connection params in /ctsms/ctsms_settings/ctsms-applicationcontext.properties (tomcat restart needed):

database_username=ctsms
database_password=ctsms
database_connection_url=jdbc:postgresql://localhost/ctsms
c3p0.acquireIncrement=3
c3p0.initialPoolSize=10
c3p0.minPoolSize=5
c3p0.maxPoolSize=30
c3p0.maxIdleTime=300
c3p0.maxStatementsPerConnection=200

(by adding params, you can override the defaults from https://github.com/phoenixctms/ctsms/blob/master/core/src/main/resources/ctsms-applicationcontext.properties )

application is known to be free of deadlocks (strict row lock order etc.)

**Comment by rkrenn** [comment]
i was able to start it on amazon e2c instance:

-Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-2581aa40 t2.medium instance,
-all default settings, default 8gb ssd storage, http and https enabled

it's surprisingly fast btw.

the problems were:
-postgres was not installed, as the postgres repos were for debian. ubuntu provides postgres-9.5 by default
-the Phoenix bulk-processor requires a newer threads::shared perl module and CPU::Affinity which is not available in Ubuntu
-apt-get update must be executed once, otherwise apache connector module packages are not found

the install.sh was fixed accordingly (https://github.com/phoenixctms/install-debian/commits/master).

so it will work now; after firing up the instance, you just need to run:

wget https://raw.githubusercontent.com/phoenixctms/install-debian/master/install.sh -O ~/install.sh
chmod 744 ~/install.sh
sudo ~/install.sh

note:
-the link printed in the console at last does not show the e2c instance's public ip, you need to look it up from the aws management console.
-when accessing the application it will display "Restricted access (xxx.xxx.xxx.xxx)" in the upper area, so you cant view or edit subjects. in order to view and edit subject personal identifyable information, you need to add your laptop's public ip to /ctssm/ctsms_properties/ctsms-trustedhosts.properties, after initially copying it from https://github.com/phoenixctms/ctsms/blob/master/core/src/main/resources/ctsms-trustedhosts.properties

it could look like this then:

localhost=localhost,127.0.0.1,0:0:0:0:0:0:0:1,::1

#your ip:
my_ip=123.123.123.123

private_10_8=10.0.0.0-10.255.255.255
private_172_12=172.16.0.0-172.31.255.255
private_192_16=192.168.0.0-192.168.255.255

all_trusted_hosts=localhost,private_10_8,private_172_12,private_192_16,my_ip

**Comment by wolass** [comment]
This is great ! thank you very much!  I think it will also be helpful for others.

**Comment by rkrenn** [comment]
would you like to try it to confirm?

**Comment by wolass** [comment]
I'm running the script right now and will report back

**Comment by wolass** [comment]
Yes, I can confirm that it worked like a charm. Thank you !

I have logged once into the system but then I got logged out and the login information does not work anymore (captcha is showing up now with the second loggin attempt). Is this an intended behaviour? I dod not change any passwords after logging in.

**Comment by rkrenn** [comment]
cool.

>Is this an intended behaviour?
yes its one-time password; used up after the first login.

you can from cli create another user, but need the "department passphrase" printed at the end of the installation, eg "The department passphrase for 'my_department' when adding users with /ctsms/dbtool.sh is 'M1JYuTkNkYKMfatXOTa7KNsdabZthLHr'."

run the below command after replacing $DEPARTMENT_PASSWORD with your dept passphrase, and $USER_PASSWORD with the desired password for the new additional user phoenix1.

sudo -u ctsms /ctsms/dbtool.sh -cu -dlk my_department -dp "$DEPARTMENT_PASSWORD" -u "phoenix1" -p "$USER_PASSWORD" -pp "INVENTORY_MASTER_ALL_DEPARTMENTS,STAFF_MASTER_ALL_DEPARTMENTS,COURSE_MASTER_ALL_DEPARTMENTS,TRIAL_MASTER_ALL_DEPARTMENTS,PROBAND_MASTER_ALL_DEPARTMENTS,USER_ALL_DEPARTMENTS,INPUT_FIELD_MASTER,INVENTORY_MASTER_SEARCH,STAFF_MASTER_SEARCH,COURSE_MASTER_SEARCH,TRIAL_MASTER_SEARCH,PROBAND_MASTER_SEARCH,USER_MASTER_SEARCH,INPUT_FIELD_MASTER_SEARCH"

**Comment by rkrenn** [comment]
coll, closing this.
