### ISSUE TITLE
Don't find a way to register a visit for a given proband

### ISSUE THREAD

**Issue by s-degoul** [phoenixctms/ctsms#5]
Hi. I am testing Phoenix with fake data in our little hospital research center, and I have not found the way to register a visit (defined in the "Visits" tab and planned in the "Visit schedule" tab) performed at a given date for a given proband. Most of trials in our center are indeed promoted by external research centers, and in that case, the CTMS only aims to list probands associated with their visits without registering any research data (destined for external eCRF).
Regards.

**Comment by rkrenn** [comment]
hi, for such scenarios, prepare one "Proband Group" per subject, ie.
- prepare a group "Subject 1"
- prepare a visit "Visit 1"
- in the "visit schedule" tab, create a visit schedule item for Visit 1 - Subject 1 - Day 1
- for demostration: create another visit schedule item for Visit 1 - Subject 1 - Day 2

finally, in the proband list tab, enroll the first subject, and assign it to the "Subject 1" group.

**Comment by s-degoul** [comment]
Thanks for your fast reply.
But, even in "normal" Phoenix scenario, is this information (date of each visit of each proband) registered in the system? If so, how can we look at the visit schedule of a given proband, retrospectively? Or how can we check that each visit for each proband was performed as expected?
I have only found a global information about proband progress, that is the status history.

**Comment by rkrenn** [comment]
correct, the "visit schedule" tab of a proband is the right place to look.

- start and stop are the dates from the visit schedule item 
- status ist the enrollment status of the subject *at that time* (see below). you can set the enrollment status in the proband list, where you added the proband to the trial.

![grafik](https://user-images.githubusercontent.com/17864099/46666355-c4c4e000-cbc6-11e8-99d4-eaafbcc1dbc3.png)

**Comment by rkrenn** [comment]
>Or how can we check that each visit for each proband was performed as expected?
usually we do that within the eCRF for the corresponding visit.
if you don't wnat to use the built-in eCRFs, but still want to track something like "visit X done y/n", i suggest you prepare a checkbox "input field". then add it ie. 3 times (for 3 visits) in the "Proband List Columns" tab of the trial. This concept is like a "mini eCRF". You can then check the corresponding field in the "Proband List Columns" tab of the proband list; after the visit was performed.

You can print these mini-forms as pdf or view entered values at a glance by selecting a column to display in the proband list (that's why it was called "Proband List Columns").

![grafik](https://user-images.githubusercontent.com/17864099/46667732-ce504700-cbca-11e8-99f3-d87fbd76d258.png)
